name: CI

on:
  push:
    branches: ['main']

  workflow_dispatch:

jobs:
  build: 
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      
      - name: A simple greeting
        run: echo Hi there!

      - name: A simples goodbye
        run: echo Goodbye!
